#!/bin/sh

### BEGIN INIT INFO
# Provides:     raspwave
# Required-Start:   $local_fs
# Required-Stop:    $local_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    Start raspwave on boot and stop it on shutdown
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

NH_LOCKFILE=/var/run/raspwave_nh.pid
RASPWAVE_LOCKFILE=/var/run/raspwave.pid

killtree() {
    local _sig=$1
    local _pid=$2
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_sig} ${_child}
    done
    echo "/bin/kill -${_sig} ${_pid}"
    sudo kill -${_sig} ${_pid}
}

case "${1}" in
    start)
        if [ -e $NH_LOCKFILE ]; then
            NH_PID=`cat $NH_LOCKFILE`
            echo "NH already running: $NH_PID"
        else
            /etc/raspwave/pylib/NotificationHandler.py&
            NH_PID=$!
            echo $NH_PID > "$NH_LOCKFILE"
            echo "Started NH with PID=$NH_PID"
        fi
        if [ -e $RASPWAVE_LOCKFILE ]; then
            RASPWAVE_PID=`cat $RASPWAVE_LOCKFILE`
            echo "raspwave already running: $RASPWAVE_PID"
        else
            /usr/local/bin/raspwave& 
            RASPWAVE_PID=$!
            echo $RASPWAVE_PID > "$RASPWAVE_LOCKFILE"
            echo "Started raspwave with PID=$RASPWAVE_PID"
        fi
        break
        ;;
    stop)
        if [ -r $NH_LOCKFILE ]; then
            NH_PID=`cat $NH_LOCKFILE`
            echo "Stopping NH with PID=$NH_PID"
            killtree 15 $NH_PID
            rm -rf $NH_LOCKFILE
        fi
        if [ -r $RASPWAVE_LOCKFILE ]; then
            RASPWAVE_PID=`cat $RASPWAVE_LOCKFILE`
            echo "Stopping raspwave with PID=$RASPWAVE_PID"
            killtree 15 $RASPWAVE_PID
            rm -rf $RASPWAVE_LOCKFILE
        fi
        break
        ;;
    restart|force-reload)
        $0 stop
        /bin/sleep 5
        $0 start
        ;;
    *)
        echo "Usage: ${0} {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
