#!/usr/bin/env bash

DATE=$(date +"%m%d%y%H%M%S")
VERSION=1.1-$DATE
ETC_RASPWAVE=debian/etc/raspwave
ETC_RASPWAVE_OPENZWAVE=debian/etc/raspwave/openzwave
USR_LOCAL_BIN=debian/usr/local/bin
USR_LOCAL_LIB_RASPWAVE=debian/usr/local/lib/raspwave
ETC_INITD=debian/etc/init.d
VAR=debian/var
VAR_WWW_RASPWAVE=debian/var/www/raspwave
VAR_LOG_RASPWAVE=debian/var/log/raspwave
ETC_LOGROTATED=debian/etc/logrotate.d

rm -rf debian

mkdir -p $ETC_RASPWAVE
cp -aR ../conf/ $ETC_RASPWAVE
cp -aR ../cronbots/ $ETC_RASPWAVE
cp -aR ../db/ $ETC_RASPWAVE
cp -aR ../robots/ $ETC_RASPWAVE
cp -aR ../scripts/ $ETC_RASPWAVE
cp -aR ../www/ $ETC_RASPWAVE
cp -aR ../pylib/ $ETC_RASPWAVE

mkdir -p $USR_LOCAL_BIN
mkdir -p $USR_LOCAL_LIB_RASPWAVE
cp -a ../sh/raspwave $USR_LOCAL_BIN
cp -a ../sh/raspscpt $USR_LOCAL_BIN
cp -a ../openzwave/.lib/MinOZW $USR_LOCAL_BIN
cp -a ../openzwave/libopenzwave.so.1.2 $USR_LOCAL_LIB_RASPWAVE
cp -a ../openzwave/libopenzwave.a $USR_LOCAL_LIB_RASPWAVE
ln -s /usr/local/lib/raspwave/libopenzwave.so.1.2 $USR_LOCAL_LIB_RASPWAVE/libopenzwave.so  

mkdir -p $ETC_RASPWAVE_OPENZWAVE
cp -aR ../openzwave/config/ $ETC_RASPWAVE_OPENZWAVE

#mkdir -p $VAR
#cp -aR ../www/ $VAR

mkdir -p $VAR_WWW_RASPWAVE
cp -ar ../www/* $VAR_WWW_RASPWAVE

mkdir -p $ETC_INITD
cp -a ../init.d/raspwave $ETC_INITD
chmod 755 $ETC_INITD/raspwave

mkdir -p $ETC_LOGROTATED
cp -a ../logrotate.d/raspwave $ETC_LOGROTATED

mkdir -p $VAR_LOG_RASPWAVE

mkdir -p debian/DEBIAN
find ./debian -type d | xargs chmod 755
sed -i "/Version:/cVersion: ${VERSION}" control
cp -a control debian/DEBIAN
cp -a postinst debian/DEBIAN
cp -a prerm debian/DEBIAN

dpkg-deb --build debian
mv debian.deb raspwave_${VERSION}.deb
echo "Created package raspwave_${VERSION}.deb"
